# NumPy: Introdução e Manipulação de Arrays
O NumPy é uma biblioteca fundamental para computação científica em Python. Ela fornece suporte eficiente para a criação, manipulação e cálculos em arrays multidimensionais. Vamos começar com alguns conceitos básicos e exemplos de uso:

## Importação
Antes de começarmos a utilizar o NumPy, precisamos importar a biblioteca. Podemos fazer isso usando a seguinte linha de código:

In [1]:
import numpy as np

Agora estamos prontos para começar!

## Criação de Arrays
O NumPy oferece várias maneiras de criar arrays. Aqui estão alguns exemplos:

In [12]:
# Criando um array a partir de uma lista
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [13]:
# Criando um array com valores sequenciais
arr2 = np.arange(0, 10, 2)  # Valores de 0 a 10 (exclusivo) com passo de 2
arr2

array([0, 2, 4, 6, 8])

In [14]:
# Criando um array de zeros
arr3 = np.zeros((3, 3))  # Array 3x3 preenchido com zeros
arr3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
# Criando um array de uns
arr4 = np.ones((2, 4))  # Array 2x4 preenchido com uns
arr4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
# Criando um array com valores aleatórios
arr5 = np.random.rand(5)  # Array de 5 elementos com valores aleatórios entre 0 e 1
arr5

array([0.43875105, 0.90308562, 0.63414617, 0.67058613, 0.67755649])

In [17]:
# Criando um array com valores espaçados
arr6 = np.linspace(0, 1, 6)  # Valores espaçados igualmente entre 0 e 1 com 6 elementos
arr6

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

## Manipulação de Arrays
O NumPy permite manipular arrays de várias maneiras. Aqui estão alguns exemplos:

In [18]:
# Acessando elementos
print(arr1[0])  # Acessa o primeiro elemento do array

1


In [19]:
# Acessando fatias
print(arr2[2:5])  # Acessa os elementos do índice 2 ao 4

[4 6 8]


In [21]:
# Modificando elementos
arr3[1, 1] = 5  # Modifica o valor do elemento na posição (1, 1)
arr3

array([[0., 0., 0.],
       [0., 5., 0.],
       [0., 0., 0.]])

In [22]:
# Operações com arrays
arr4 = arr1 + arr2  # Soma os elementos de arr1 e arr2 elemento por elemento
arr4

array([ 1,  4,  7, 10, 13])

In [23]:
# Reshape de arrays
arr5 = np.arange(10)
arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr6 = arr5.reshape((2, 5))  # Redimensiona o array para uma matriz 2x5
arr6

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
# Operações matemáticas
arr7 = np.sin(arr5)  # Calcula o seno de cada elemento do array
arr7

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [26]:
arr8 = np.exp(arr6)  # Calcula a exponencial de cada elemento da matriz
arr8

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03]])

In [27]:
# Funções estatísticas
mean = np.mean(arr5)  # Calcula a média dos elementos do array
mean

4.5

In [28]:
std = np.std(arr6)  # Calcula o desvio padrão dos elementos da matriz
std

2.8722813232690143

Neste exemplo, importamos o NumPy, criamos arrays usando diferentes métodos, manipulamos os arrays realizando operações, acessando elementos e fatias, modificando valores, realizando operações matemáticas e aplicando funções estatísticas.

# Pandas: Introdução e Manipulação de Dados Tabulares
O Pandas é uma biblioteca poderosa para análise e manipulação de dados em Python. Ele oferece estruturas de dados flexíveis e eficientes, como o DataFrame, que permite trabalhar com dados tabulares de forma fácil e intuitiva. Vamos começar com alguns conceitos básicos e exemplos de uso:

## Importação
Antes de começarmos a utilizar o Pandas, precisamos importar a biblioteca. Podemos fazer isso usando a seguinte linha de código:

In [4]:
import pandas as pd

## Leitura de Dados
O Pandas oferece várias maneiras de ler dados de diferentes fontes. Aqui estão alguns exemplos:



In [8]:
# Lendo um arquivo CSV
#df1 = pd.read_csv('dados.csv')

# Lendo um arquivo Excel
#df2 = pd.read_excel('dados.xlsx')

# Lendo dados de uma URL
url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
df = pd.read_csv(url)

## Exploração de Dados
Depois de carregar os dados, podemos explorá-los usando várias funcionalidades do Pandas:

In [11]:
# Visualizando as primeiras linhas do DataFrame
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [29]:
# Visualizando as últimas linhas do DataFrame
df.tail()

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [30]:
# Verificando as dimensões do DataFrame
df.shape

(891, 12)

In [31]:
# Verificando os nomes das colunas
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [32]:
# Verificando os tipos de dados das colunas
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [33]:
# Resumo estatístico do DataFrame
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [36]:
# Contagem de valores únicos em uma coluna
df['Fare'].value_counts()

8.0500     43
13.0000    42
7.8958     38
7.7500     34
26.0000    31
           ..
35.0000     1
28.5000     1
6.2375      1
14.0000     1
10.5167     1
Name: Fare, Length: 248, dtype: int64

## Manipulação de Dados
O Pandas oferece várias funcionalidades para manipular os dados em um DataFrame:

In [38]:
# Selecionando colunas específicas
df[['Name', 'Sex']]

Name     Sex
0                              Braund, Mr. Owen Harris    male
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2                               Heikkinen, Miss. Laina  female
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
4                             Allen, Mr. William Henry    male
..                                                 ...     ...
886                              Montvila, Rev. Juozas    male
887                       Graham, Miss. Margaret Edith  female
888           Johnston, Miss. Catherine Helen "Carrie"  female
889                              Behr, Mr. Karl Howell    male
890                                Dooley, Mr. Patrick    male

[891 rows x 2 columns]

In [42]:
# Filtrando dados com base em condições
df[df['Age'] > 10.0]

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
885          886         0       3   
886          887         0       2   
887          888         1       1   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
885      5            382652  29.1250   NaN        Q  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[650 rows x 12 columns]

In [44]:
# Ordenando o DataFrame
df.sort_values('Name', ascending=True)

PassengerId  Survived  Pclass                                   Name  \
845          846         0       3                    Abbing, Mr. Anthony   
746          747         0       3            Abbott, Mr. Rossmore Edward   
279          280         1       3       Abbott, Mrs. Stanton (Rosa Hunt)   
308          309         0       2                    Abelson, Mr. Samuel   
874          875         1       2  Abelson, Mrs. Samuel (Hannah Wizosky)   
..           ...       ...     ...                                    ...   
286          287         1       3                de Mulder, Mr. Theodore   
282          283         0       3              de Pelsmaeker, Mr. Alfons   
361          362         0       2              del Carlo, Mr. Sebastiano   
153          154         0       3        van Billiard, Mr. Austin Blyler   
868          869         0       3            van Melkebeke, Mr. Philemon   

        Sex   Age  SibSp  Parch         Ticket     Fare Cabin Embarked  
845    male  42.0      0      0      C.A. 5547   7.5500   NaN        S  
746    male  16.0      1      1      C.A. 2673  20.2500   NaN        S  
279  female  35.0      1      1      C.A. 2673  20.2500   NaN        S  
308    male  30.0      1      0      P/PP 3381  24.0000   NaN        C  
874  female  28.0      1      0      P/PP 3381  24.0000   NaN        C  
..      ...   ...    ...    ...            ...      ...   ...      ...  
286    male  30.0      0      0         345774   9.5000   NaN        S  
282    male  16.0      0      0         345778   9.5000   NaN        S  
361    male  29.0      1      0  SC/PARIS 2167  27.7208   NaN        C  
153    male  40.5      0      2       A/5. 851  14.5000   NaN        S  
868    male   NaN      0      0         345777   9.5000   NaN        S  

[891 rows x 12 columns]

In [45]:
# Ordenando o DataFrame
df.sort_values('Name', ascending=False)

PassengerId  Survived  Pclass                                   Name  \
868          869         0       3            van Melkebeke, Mr. Philemon   
153          154         0       3        van Billiard, Mr. Austin Blyler   
361          362         0       2              del Carlo, Mr. Sebastiano   
282          283         0       3              de Pelsmaeker, Mr. Alfons   
286          287         1       3                de Mulder, Mr. Theodore   
..           ...       ...     ...                                    ...   
874          875         1       2  Abelson, Mrs. Samuel (Hannah Wizosky)   
308          309         0       2                    Abelson, Mr. Samuel   
279          280         1       3       Abbott, Mrs. Stanton (Rosa Hunt)   
746          747         0       3            Abbott, Mr. Rossmore Edward   
845          846         0       3                    Abbing, Mr. Anthony   

        Sex   Age  SibSp  Parch         Ticket     Fare Cabin Embarked  
868    male   NaN      0      0         345777   9.5000   NaN        S  
153    male  40.5      0      2       A/5. 851  14.5000   NaN        S  
361    male  29.0      1      0  SC/PARIS 2167  27.7208   NaN        C  
282    male  16.0      0      0         345778   9.5000   NaN        S  
286    male  30.0      0      0         345774   9.5000   NaN        S  
..      ...   ...    ...    ...            ...      ...   ...      ...  
874  female  28.0      1      0      P/PP 3381  24.0000   NaN        C  
308    male  30.0      1      0      P/PP 3381  24.0000   NaN        C  
279  female  35.0      1      1      C.A. 2673  20.2500   NaN        S  
746    male  16.0      1      1      C.A. 2673  20.2500   NaN        S  
845    male  42.0      0      0      C.A. 5547   7.5500   NaN        S  

[891 rows x 12 columns]

In [46]:
# Agrupando dados e aplicando funções
df.groupby('Survived').mean()

<ipython-input-46-2f7a8b1c0917>:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('Survived').mean()


PassengerId    Pclass        Age     SibSp     Parch       Fare
Survived                                                                 
0          447.016393  2.531876  30.626179  0.553734  0.329690  22.117887
1          444.368421  1.950292  28.343690  0.473684  0.464912  48.395408

In [48]:
# Preenchendo valores ausentes
df.fillna('Cabin')

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex    Age  SibSp  \
0                              Braund, Mr. Owen Harris    male   22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female   38.0      1   
2                               Heikkinen, Miss. Laina  female   26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   35.0      1   
4                             Allen, Mr. William Henry    male   35.0      0   
..                                                 ...     ...    ...    ...   
886                              Montvila, Rev. Juozas    male   27.0      0   
887                       Graham, Miss. Margaret Edith  female   19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female  Cabin      1   
889                              Behr, Mr. Karl Howell    male   26.0      0   
890                                Dooley, Mr. Patrick    male   32.0      0   

     Parch            Ticket     Fare  Cabin Embarked  
0        0         A/5 21171   7.2500  Cabin        S  
1        0          PC 17599  71.2833    C85        C  
2        0  STON/O2. 3101282   7.9250  Cabin        S  
3        0            113803  53.1000   C123        S  
4        0            373450   8.0500  Cabin        S  
..     ...               ...      ...    ...      ...  
886      0            211536  13.0000  Cabin        S  
887      0            112053  30.0000    B42        S  
888      2        W./C. 6607  23.4500  Cabin        S  
889      0            111369  30.0000   C148        C  
890      0            370376   7.7500  Cabin        Q  

[891 rows x 12 columns]

In [56]:
df = pd.read_csv(url)

In [50]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [52]:
# Removendo linhas ou colunas com valores ausentes
df.dropna()

PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
6              7         0       1   
10            11         1       3   
11            12         1       1   
..           ...       ...     ...   
871          872         1       1   
872          873         0       1   
879          880         1       1   
887          888         1       1   
889          890         1       1   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
..                                                 ...     ...   ...    ...   
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1   
872                           Carlsson, Mr. Frans Olof    male  33.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   

     Parch    Ticket     Fare        Cabin Embarked  
1        0  PC 17599  71.2833          C85        C  
3        0    113803  53.1000         C123        S  
6        0     17463  51.8625          E46        S  
10       1   PP 9549  16.7000           G6        S  
11       0    113783  26.5500         C103        S  
..     ...       ...      ...          ...      ...  
871      1     11751  52.5542          D35        S  
872      0       695   5.0000  B51 B53 B55        S  
879      1     11767  83.1583          C50        C  
887      0    112053  30.0000          B42        S  
889      0    111369  30.0000         C148        C  

[183 rows x 12 columns]

In [58]:
# Criando novas colunas
df['SurvivedPclass'] = df['Survived'] + df['Pclass']
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  SurvivedPclass  
0        0         A/5 21171   7.2500   NaN        S               3  
1        0          PC 17599  71.2833   C85        C               2  
2        0  STON/O2. 3101282   7.9250   NaN        S               4  
3        0            113803  53.1000  C123        S               2  
4        0            373450   8.0500   NaN        S               3  
..     ...               ...      ...   ...      ...             ...  
886      0            211536  13.0000   NaN        S               2  
887      0            112053  30.0000   B42        S               2  
888      2        W./C. 6607  23.4500   NaN        S               3  
889      0            111369  30.0000  C148        C               2  
890      0            370376   7.7500   NaN        Q               3  

[891 rows x 13 columns]